[build]
  command = "pip install -r requirements.txt"
  # 'publish' can be your static directory, this is usually fine.
  # It tells Netlify where to look if it's serving static files directly.
  # Your Flask app will also serve static files via url_for, but Netlify's CDN can be faster for these.
  publish = "bus_sim_back/static" 
  
  # CRITICAL: If you are NOT using Netlify Serverless Functions for your Flask app
  # (and your Procfile indicates you want a Gunicorn server),
  # REMOVE or COMMENT OUT any 'functions' line.
  # functions = "netlify/functions" # <--- Try removing this line

[build.environment]
  PYTHON_VERSION = "3.10" 
  # You could also try more specific patch like "3.10.13" if "3.10" alone doesn't make it pick one.
  # But since 3.10.18 was found for pip, "3.10" should be fine.